use std::collections::HashMap;
use std::path::PathBuf;
use std::process::{Child, Command, Stdio};

pub struct WallpaperEngine {
    // Stores active process handle per output
    processes: HashMap<String, Child>,
}

impl WallpaperEngine {
    pub fn new() -> Self {
        Self {
            processes: HashMap::new(),
        }
    }

    pub fn set_wallpaper(
        &mut self,
        output: &str,
        video_path: &str,
        scaling: &str,
        mute: bool,
        hwdec: &str,
    ) -> Result<u32, std::io::Error> {
        // Kill existing instance for this specific output first
        self.stop_output(output);

        let mut opts = format!("loop-file=inf --hwdec={} --no-config", hwdec);
        if mute {
            opts.push_str(" --no-audio");
        }

        match scaling {
            "fill" => opts.push_str(" --panscan=1.0"),
            "stretch" => opts.push_str(" --no-keepaspect"),
            _ => {} // fit is default
        }

        let child = Command::new("mpvpaper")
            .arg("-o")
            .arg(&opts)
            .arg(output)
            .arg(video_path)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()?;

        let pid = child.id();
        self.processes.insert(output.to_string(), child);
        Ok(pid)
    }

    pub fn stop_output(&mut self, output: &str) {
        if let Some(mut child) = self.processes.remove(output) {
            let _ = child.kill();
        }
    }

    pub fn stop_all(&mut self) {
        for (_, mut child) in self.processes.drain() {
            let _ = child.kill();
        }
        // Also cleanup external or orphaned mpvpaper processes
        let _ = Command::new("pkill")
            .arg("-x")
            .arg("mpvpaper")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }

    pub fn write_autostart(&self, wallpapers: &HashMap<String, String>, scaling: &HashMap<String, String>, mute: bool, hwdec: &str) -> std::io::Result<()> {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        let autostart_dir = PathBuf::from(&home).join(".config").join("autostart");
        let script_dir = PathBuf::from(&home).join(".config").join("aura");

        std::fs::create_dir_all(&autostart_dir)?;
        std::fs::create_dir_all(&script_dir)?;

        let script_path = script_dir.join("autostart.sh");
        let mut script_content = String::from("#!/usr/bin/env bash\n# Generated by Aura - COSMIC Live Wallpaper\nset -e\n\n");

        for (output, path) in wallpapers {
            let sc = scaling.get(output).map(|s| s.as_str()).unwrap_or("fit");
            let mut opts = format!("loop-file=inf --hwdec={} --no-config", hwdec);
            if mute {
                opts.push_str(" --no-audio");
            }
            if sc == "fill" {
                opts.push_str(" --panscan=1.0");
            } else if sc == "stretch" {
                opts.push_str(" --no-keepaspect");
            }

            script_content.push_str(&format!(
                "mpvpaper --fork -o \"{}\" \"{}\" \"{}\"\n",
                opts, output, path
            ));
        }

        std::fs::write(&script_path, script_content)?;

        // Set chmod +x on Unix
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&script_path)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&script_path, perms)?;
        }

        let desktop_file = autostart_dir.join("io.github.antwny.aura.desktop");
        let desktop_content = format!(
            "[Desktop Entry]\n\
            Type=Application\n\
            Name=Aura Live Wallpaper\n\
            Exec={}\n\
            Icon=preferences-desktop-wallpaper\n\
            Terminal=false\n\
            X-GNOME-Autostart-enabled=true\n\
            Categories=Utility;DesktopSettings;\n",
            script_path.display()
        );

        std::fs::write(desktop_file, desktop_content)?;
        Ok(())
    }

    pub fn remove_autostart() -> std::io::Result<()> {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        let desktop_file = PathBuf::from(home).join(".config").join("autostart").join("io.github.antwny.aura.desktop");
        if desktop_file.exists() {
            std::fs::remove_file(desktop_file)?;
        }
        Ok(())
    }

    pub fn is_autostart_enabled() -> bool {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        PathBuf::from(home).join(".config").join("autostart").join("io.github.antwny.aura.desktop").exists()
    }
}
