use std::collections::HashMap;
use std::path::PathBuf;
use std::process::{Child, Command, Stdio};

pub struct WallpaperEngine {
    // Stores active process handle per output
    processes: HashMap<String, Child>,
    pub is_paused: bool,
}

impl WallpaperEngine {
    pub fn new() -> Self {
        Self {
            processes: HashMap::new(),
            is_paused: false,
        }
    }

    pub fn set_wallpaper(
        &mut self,
        output: &str,
        video_path: &str,
        scaling: &str,
        mute: bool,
        hwdec: &str,
    ) -> Result<u32, std::io::Error> {
        // Kill existing instance for this specific output first
        self.stop_output(output);

        let is_image = std::path::Path::new(video_path)
            .extension()
            .and_then(|e| e.to_str())
            .map(|ext| crate::scanner::IMAGE_EXTENSIONS.contains(&ext.to_lowercase().as_str()))
            .unwrap_or(false);

        let opts = Self::build_mpv_options(scaling, mute, hwdec, is_image);

        let child = match Command::new("mpvpaper")
            .arg("-p") // Wayland layer-shell compositor native auto-pause when obscured
            .arg("-o")
            .arg(&opts)
            .arg(output)
            .arg(video_path)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn() {
                Ok(c) => c,
                Err(e) => {
                    eprintln!("[Aura Engine] Error al iniciar mpvpaper: {} (output: {}, video: {})", e, output, video_path);
                    return Err(e);
                }
            };

        let pid = child.id();
        self.processes.insert(output.to_string(), child);
        self.is_paused = false;
        Ok(pid)
    }

    #[allow(dead_code)]
    pub fn is_running(&self) -> bool {
        !self.processes.is_empty()
    }

    pub fn toggle_pause(&mut self) -> bool {
        if self.is_paused {
            self.resume_all();
            false
        } else {
            self.pause_all();
            true
        }
    }

    pub fn pause_all(&mut self) {
        // Send SIGSTOP to freeze video playback and reduce GPU/CPU load to 0%
        for (_, child) in &self.processes {
            let pid = child.id().to_string();
            let _ = Command::new("kill").args(["-STOP", &pid]).status();
        }
        let _ = Command::new("pkill").args(["-STOP", "-x", "mpvpaper"]).status();
        self.is_paused = true;
    }

    pub fn resume_all(&mut self) {
        // Send SIGCONT to smoothly unfreeze playback
        for (_, child) in &self.processes {
            let pid = child.id().to_string();
            let _ = Command::new("kill").args(["-CONT", &pid]).status();
        }
        let _ = Command::new("pkill").args(["-CONT", "-x", "mpvpaper"]).status();
        self.is_paused = false;
    }

    pub fn stop_output(&mut self, output: &str) {
        if let Some(mut child) = self.processes.remove(output) {
            let _ = child.kill();
        }
    }

    pub fn stop_all(&mut self) {
        for (_, mut child) in self.processes.drain() {
            let _ = child.kill();
        }
        // Also cleanup external or orphaned mpvpaper processes
        let _ = Command::new("pkill")
            .arg("-x")
            .arg("mpvpaper")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
        self.is_paused = false;
    }

    pub fn build_mpv_options(scaling: &str, mute: bool, hwdec: &str, is_image: bool) -> String {
        let mut opts = if is_image {
            String::from("image-display-duration=inf --pause=yes --no-config --no-audio")
        } else {
            let mut o = format!("loop-file=inf --hwdec={} --no-config", hwdec);
            if mute {
                o.push_str(" --no-audio");
            }
            o
        };

        match scaling {
            "fill" => opts.push_str(" --panscan=1.0"),
            "stretch" => opts.push_str(" --no-keepaspect"),
            _ => {} // fit is default
        }
        opts
    }

    pub fn write_autostart(&self, wallpapers: &HashMap<String, String>, scaling: &HashMap<String, String>, mute: bool, hwdec: &str) -> std::io::Result<()> {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        let autostart_dir = PathBuf::from(&home).join(".config").join("autostart");
        let script_dir = PathBuf::from(&home).join(".config").join("aura");

        std::fs::create_dir_all(&autostart_dir)?;
        std::fs::create_dir_all(&script_dir)?;

        let script_path = script_dir.join("autostart.sh");
        let mut script_content = String::from("#!/usr/bin/env bash\n# Generated by Aura - COSMIC Live Wallpaper\nset -e\n\n");

        for (output, path) in wallpapers {
            let sc = scaling.get(output).map(|s| s.as_str()).unwrap_or("fit");
            let is_image = std::path::Path::new(path)
                .extension()
                .and_then(|e| e.to_str())
                .map(|ext| crate::scanner::IMAGE_EXTENSIONS.contains(&ext.to_lowercase().as_str()))
                .unwrap_or(false);
            let opts = Self::build_mpv_options(sc, mute, hwdec, is_image);

            script_content.push_str(&format!(
                "mpvpaper -p --fork -o {} {} {}\n",
                shell_escape(&opts),
                shell_escape(output),
                shell_escape(path)
            ));
        }

        std::fs::write(&script_path, script_content)?;

        // Set chmod +x on Unix
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&script_path)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&script_path, perms)?;
        }

        let desktop_file = autostart_dir.join("io.github.antwny.aura.desktop");
        let desktop_content = format!(
            "[Desktop Entry]\n\
            Type=Application\n\
            Name=Aura Live Wallpaper\n\
            Exec={}\n\
            Icon=io.github.antwny.aura\n\
            Terminal=false\n\
            X-GNOME-Autostart-enabled=true\n\
            Categories=Utility;DesktopSettings;\n",
            script_path.display()
        );

        std::fs::write(desktop_file, desktop_content)?;
        Ok(())
    }

    pub fn remove_autostart() -> std::io::Result<()> {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        let desktop_file = PathBuf::from(home).join(".config").join("autostart").join("io.github.antwny.aura.desktop");
        if desktop_file.exists() {
            std::fs::remove_file(desktop_file)?;
        }
        Ok(())
    }

    pub fn is_autostart_enabled() -> bool {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        PathBuf::from(home).join(".config").join("autostart").join("io.github.antwny.aura.desktop").exists()
    }
}

pub fn shell_escape(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_mpv_options() {
        let opts_fit_mute = WallpaperEngine::build_mpv_options("fit", true, "auto-safe", false);
        assert!(opts_fit_mute.contains("--hwdec=auto-safe"));
        assert!(opts_fit_mute.contains("--no-audio"));
        assert!(!opts_fit_mute.contains("--panscan"));

        let opts_fill_sound = WallpaperEngine::build_mpv_options("fill", false, "vaapi", false);
        assert!(opts_fill_sound.contains("--hwdec=vaapi"));
        assert!(!opts_fill_sound.contains("--no-audio"));
        assert!(opts_fill_sound.contains("--panscan=1.0"));

        let opts_stretch = WallpaperEngine::build_mpv_options("stretch", false, "nvdec", false);
        assert!(opts_stretch.contains("--no-keepaspect"));

        let opts_image = WallpaperEngine::build_mpv_options("fill", true, "auto-safe", true);
        assert!(opts_image.contains("image-display-duration=inf"));
        assert!(opts_image.contains("--pause=yes"));
        assert!(opts_image.contains("--panscan=1.0"));
    }

    #[test]
    fn test_shell_escape_safety() {
        assert_eq!(shell_escape("normal_string"), "'normal_string'");
        assert_eq!(shell_escape("with space"), "'with space'");
        assert_eq!(shell_escape("with$dollar"), "'with$dollar'");
        assert_eq!(shell_escape("with`backtick`"), "'with`backtick`'");
        assert_eq!(shell_escape("with'quote"), "'with'\\''quote'");
    }
}
